DROP TABLE IF EXISTS badquota.t1;
DROP TABLE IF EXISTS badbody_schema.t2;
DROP ROLE IF EXISTS testbody;
DROP SCHEMA IF EXISTS badquota;
DROP ROLE IF EXISTS badbody;
DROP SCHEMA IF EXISTS badbody_scehma;
DROP SCHEMA IF EXISTS deleteschema;
DROP SCHEMA IF EXISTS srs1;
DROP SCHEMA IF EXISTS srr1;
DROP SCHEMA IF EXISTS srE;
DROP SCHEMA IF EXISTS s1;
DROP SCHEMA IF EXISTS s2;
DROP SCHEMA IF EXISTS s3;
DROP SCHEMA IF EXISTS s4;
DROP SCHEMA IF EXISTS s5;
DROP SCHEMA IF EXISTS s6;
DROP SCHEMA IF EXISTS s7;

DROP TABLE IF EXISTS b;
DROP TABLE IF EXISTS b2;
DROP ROLE IF EXISTS srerole;
DROP ROLE IF EXISTS srole;
DROP ROLE IF EXISTS strole;
DROP ROLE IF EXISTS u1;
DROP ROLE IF EXISTS u2;
DROP ROLE IF EXISTS u3temp;

DROP EXTENSION diskquota;
